name: Deploy to Nginx Server

on:
  push:
    branches:
      - main  # 监听main分支的push事件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码到runner

      - name: Set up Node.js
        uses: actions/setup-node@v4  # 设置Node环境
        with:
          node-version: '18'  # 指定Node版本

      - name: Install dependencies
        run: npm ci  # 使用ci命令确保依赖一致性

      - name: Build project
        run: npm run build  # 执行项目构建命令

      - name: Deploy to server via SFTP
        uses: appleboy/sftp-action@v0.1.8  # 使用SFTP Action
        with:
          host: ${{ secrets.SSH_HOST }}  # SFTP主机地址，从secrets获取
          username: ${{ secrets.SSH_USERNAME }}  # SFTP用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SFTP私钥
          port: ${{ secrets.SSH_PORT }}  # SFTP端口
          source: "dist/*"  # 本地源文件路径
          target: "/usr/share/nginx/html/"  # 目标路径
          rm: true  # 删除目标目录中的旧文件
